SELECT USR.RECORDID FROM SYSTEMNPVRRECORDING SYS
INNER JOIN USERNPVRRECORDING USR
ON SYS.RECORDID = USR.RECORDID
INNER JOIN (
SELECT PROGRAMEXTERNALID, PROGRAMSTARTTIME
FROM USERNPVRRECORDING U
INNER JOIN SYSTEMNPVRRECORDING S
ON U.RECORDID = S.RECORDID
WHERE U.USERID =1394899
AND U.SERIESID =128312
AND U.USERNAME LIKE '%TSPT2804316%' 
) TEMPDATA
ON SYS.PROGRAMEXTERNALID = TEMPDATA.PROGRAMEXTERNALID
AND SYS.PROGRAMSTARTTIME = TEMPDATA.PROGRAMSTARTTIME
WHERE USERID =1394899 AND SERIESID =128312
AND MARKEDFORDELETE = 0 AND USERNAME LIKE '%TSPT2804316%';